[[headers]]
  for = "/.well-known/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Content-Type = "application/json"

[[redirects]]
  from = "/.well-known/assetlinks.json"
  to = "/.well-known/assetlinks.json"
  status = 200
  force = true